### ISSUE TITLE
Unused import

### ISSUE THREAD

**Issue by moribus-single** [i-link-pro-team/hardhat-boilerplate#1]
https://github.com/i-link-pro-team/hardhat-boilerplate/blob/b67b94cd8823c7e7c7edddf86f0caf2ec44a378e/contracts/mocks/ERC20Mock.sol#L5

**Comment by MikeVini** [comment]
yes, this template was created for students of the i-link Academy, we studied aspects of the correct writing of contracts. I'm glad you noticed it, come to our next academy ;)
